backend:
  name: git-gateway
publish_mode: editorial_workflow
media_folder: "static/img"
public_folder: "/img"
collections:
  - name: "hardware" # Used in routes, e.g., /admin/collections/blog
    label: "Hardware" # Used in the UI
    folder: "content/hardware" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "thumbnail", widget: "image" }
      - { label: "Description", name: "body", widget: "markdown" }
  - name: "installs"
    label: "Installs"
    folder: "content/installs"
    create: true
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
